### ISSUE TITLE
Lucent (?) crash after walking around in game

### ISSUE THREAD

**Issue by evanbones** [spoorn/sodium-forge#108]
### Reproduction Steps
Totally randomly after walking around in game for a few seconds. It's possible that it was caused by the mod Lucent, but the mod works totally fine with sodium otherwise.

### Crash Report File
https://pastebin.com/N04ZJ69U

**Comment by evanbones** [comment]
Ok yeah, 99% sure it's Lucent. Only seems to happen when holding a torch or other light emitting block

**Comment by evanbones** [comment]
If it's not Lucent, it's probably Enhanced Celestials or True Darkness. Those are the only mods I added when the crash started occuring

**Comment by Corvus20** [comment]
Lucent says on its curseforge page that it does not work with Sodium Reforged as of right now. Unsure if compatibility is planned for the future or not.

**Comment by BugmanBugman** [comment]
I believe lucent has an API that sodium could hook into

**Comment by Inqie** [comment]
It is definitely Lucent because I had a similar problem. There's also a problem, while using Sodium, with the texture brightness of held items registered by Lucent (their brightness ignores the dynamic light). 

It's true Sodium is listed as incompatible on Lucent's page. If anyone wants a stopgap, there's another [Dynamic Lighting mod](https://www.curseforge.com/minecraft/mc-mods/dynamic-lights) that makes a different approach that works with Sodium (though possibly less performance friendly).

**Comment by jakeb072001** [comment]
lucent doesn't crash for me. the only problem is that it tanks performance while moving (from 140 to 30-50 fps) making it basically impossible to use. haven't tested lucent without sodium but I assume it doesn't have this bad of performance normally so there must be some sort of weirdness going on.

**Comment by spoorn** [comment]
Hopefully fixed in next commit, let me know if it doesn't

**Comment by evanbones** [comment]
New crash: https://pastebin.com/uepmXPN2

Pretty sure it's still related to this incomaptability
