### ISSUE TITLE
Please change the project name

### ISSUE THREAD

**Issue by jellysquid3** [spoorn/sodium-forge#111]
Hi. I am the original author of the mods which this project ports to Forge.

Many users have been confused by the fact that despite this project being called "Sodium Reforged", it actually packages Phosphor, Lithium, and Sodium all together. It also appears that it could be on your radar to add other mods like Starlight with #98, which would further worsen this situation. Rather tragically, it also leads many people to making the argument that the Forge port of Sodium is much faster than the original Fabric version, simply because it packages more of my mods by default.

I would appreciate if another name was chosen to alleviate this confusion. Thanks in advance.

**Comment by spoorn** [comment]
I forked off and inherited this Forge port with it already containing Lithium/Phosphor, both of which I've been disabling more and more as they are not up to date and I don't have the time to update it.  I'm leaning on removing Lithium/Phosphor completely as it's too hard to maintain all 3 in a single mod, rather than changing the name to indicate it contains the 3 as that would be incorrect if I removed them.  Also, I don't want to pull in Starlight in the release for the same problems

And yes, tragically people don't read any of the description that clarifies all this.  I chose the name "Sodium Reforged" to give credit to the original Sodium mod, but I can modify the title to indicate this is not 1:1 with the original since the title is all people look at most of the time.

Maybe putting a 36px disclaimer at the top will have people read some of the description 😑

**Comment by Pannoniae** [comment]
Maybe say "Sodium + additional optimisations from Lithium/Phosphor" in the description?

**Comment by spoorn** [comment]
Changed the project name and description on CurseForge, will also update the github description and project name in next commit.  Let me know if anything else needs to be changed

**Comment by jellysquid3** [comment]
@spoorn Sorry for my late response. I didn't see the reply to this in my GitHub notifications, and I tend to be quite slow with these things.

What I'm asking for is that the project simply not be called "Sodium Reforged"... because it isn't. It's a port of my mod(s) with many features/fixes applied that deviate from the original mods quite significantly. Many players are still confusing it with my mods because the shorthand of "Sodium Reforged" that everyone will go with is "Sodium" because people are treating it as a straightforward port (which it isn't). You can't avoid this unless you just avoid using the name.

Unfortunately, so long as this continues, all of the discourse around Sodium Reforged will continue to be confused with my own mod. This means that when people read online that Sodium has issues with a lot of mods, has performance issues, crashes, etc, that are only present in the Forge version, this makes a poor reflection upon my own mod. I already see this in a lot of spaces I frequent, which saddens me to some degree. I don't entirely think it's fair, either.

This isn't to say that I have a problem with Forge ports. I just don't want it to be my problem, or for players to be confused about what is what. Choosing another name more or less solves that problem, so long as you continue attributing the original source on your page.

**Comment by jellysquid3** [comment]
Just wanted to say that someone else let me know you had changed the project's name, and to drop my token of thanks for doing so.
