### ISSUE TITLE
Black artifacting around blocks with mipmap

### ISSUE THREAD

**Issue by yavincl** [spoorn/sodium-forge#39]
I'm on sodium-forge 2.2

If you look at a grass block and go a bit further from it, it will get a black bar around its grass side. This also happens with some modded blocks as seen below, and sometimes even on tall grass.

This reminds me of what I saw in game when Mojang switched to a newer version of OpenGL in that snapshot, there was this bug: https://bugs.mojang.com/browse/MC-218609

Annd... as expected, the artifacting goes away if I set the mipmap level to zero. Any other level and it's there.

![2021-06-20_19 40 23](https://user-images.githubusercontent.com/57966308/122690361-7da89d00-d1ff-11eb-88d2-4fc6fb7e4748.png)
![2021-06-20_19 30 41](https://user-images.githubusercontent.com/57966308/122690214-92d0fc00-d1fe-11eb-8f94-bd13e6c9f524.png)
![a](https://user-images.githubusercontent.com/57966308/122690215-949abf80-d1fe-11eb-910b-c0acd93ff676.png)

I have compact vertex format disabled
My computer is running Arch Linux with the latest nvidia drivers.
The modpack is Enigmatica 6 0.5.0

**Comment by spoorn** [comment]
This is due to blending of Textures with Mipped textures which was on the dev branch of Sodium Fabric.  One way to fix this is to cut off opacity at a higher value, but that causes translucent blocks to render incorrectly.  

I'm working on reverting that blending as I don't think it's adding much benefit, plus the latest branches of Sodium Fabric do not have that

**Comment by spoorn** [comment]
Fixed in https://github.com/spoorn/sodium-forge/commit/b4c5da77abf447ac0371f3b2be85addea80738aa, will be in next release

**Comment by yavincl** [comment]
Thanks a bunch!
