### ISSUE TITLE
Darkness Everywhere

### ISSUE THREAD

**Issue by WenXin20** [spoorn/sodium-forge#70]
### Expected Behavior
- Chunks to be properly lit.

### Actual Behavior
- Chunks have a light level of zero.
- Sodium is installed on both the client and the server.
- This occurred after updating from v2.5 to v2.9
- Also occurs with v2.9.1
- Downgrading back to v2.5 fixed the lighting issue.
- Maybe the disabling of lithium caused this?

### Reproduction Steps
1. Join a server world
2. Observe

### Attachments
![2021-07-04_18 28 40](https://user-images.githubusercontent.com/12000593/124413993-6f867080-dd17-11eb-987c-c95b303b372d.png)
![2021-07-04_18 29 06](https://user-images.githubusercontent.com/12000593/124413998-71e8ca80-dd17-11eb-84f3-ff8524025bd1.png)

### [Optional] Server/Client logs
- [Client latest.log](https://gist.github.com/WenXin20/360f2d3570eef1e77a93626fd4bb799c)
- [Server latest.log](https://gist.github.com/WenXin20/59678666808359aa42a954d09b350b97)

### Mods list
- Too many to list here. Any idea what mods could affect it, if any?  

### System Information

- Java Version: [1.8.0_51]
- CPU: [4x AMD A12-9720P]
- GPU: [AMD Radeon R7]
- `Sodium Reforged v2.9.1+rev.63112e3`

**Comment by spoorn** [comment]
Can you confirm if it's related to something with the Lithium mixins by setting `mixin.ai=true` in the **sodium-mixins.properties** file?

**Comment by spoorn** [comment]
You could also try editing some of the menu options, like Smooth Lighting and see if turning off Smooth Lighting fixes it

**Comment by WenXin20** [comment]
Sure, I'll give it a try

**Comment by WenXin20** [comment]
Tried both, but neither one fixed it. Just thought to mention that the F3 screen displays the light level at zero. Also noticed that Biome Blend is stuck at 2 for me, tried changing it to 7, but it reset after closing the menu using `esc` (close button didn't work either).

No smooth lightning: 
![2021-07-05_01 01 25](https://user-images.githubusercontent.com/12000593/124424402-926f4f80-dd2c-11eb-862d-58da3fc3ba1a.png)

**Comment by spoorn** [comment]
hmm, it could be a mod conflicting as I can't reproduce this in my own modpack.  Do you have your mod list?

**Comment by WenXin20** [comment]
Here it is, it's not small though: https://gist.github.com/WenXin20/1f40d17f80995d108f8dcd88a823dce4
Maybe [Ferritecore](https://www.curseforge.com/minecraft/mc-mods/ferritecore),[ Chunk Saving Fix](https://www.curseforge.com/minecraft/mc-mods/chunk-saving-fix), or [Flywheel](https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3364010)?

**Comment by spoorn** [comment]
It's probably not Ferritecore as I use that myself.  Could be one of the other 2, or do you have some resource/texture packs on?

**Comment by WenXin20** [comment]
Trying without Chunk Saving Fix now. I have several resourcepacks on, mainly personal packs I made myself, like the MC Connected resource pack.

**Comment by WenXin20** [comment]
It wasn't the one. I'll try without Flywheel tomorrow.

**Comment by mcullifer** [comment]
I have been experiencing this issue as well. I have done a lot of testing with it to see what exactly causes the issue. Here are the following observations I made. Some of the things I list are dead ends but it might help with not wasting time on if they are/aren't causing the issue.

- By the way the individual light sources appeared around my base I thought it had something to do with Feral Lanterns because on my server one of my friends bases does not have the issue, he also does not use these lanterns. After removing all the Feral Lanterns the lighting bug persists.
- I noticed when flying around it was clusters of chunks that would appear dark that seemed to be almost exactly the same as areas that were claimed and force loaded with FTB Chunks. Un-claiming and removing force loading does not affect it at all.
- This one is really important in my testing. I found out that teleporting seemed to trigger this lighting bug. I could not reproduce it with nether portals. I am however able to reproduce it constantly with Waystones and the Mekanism teleporter. Not only that but the bug happens routinely on every 3rd or 4th teleport. I found this very strange you can teleport a few times and everything is normal but on the 3rd or 4th teleport the area is dark. Then it will fix again after teleporting away and back to the same spot.
- I also figured out when I had the lighting bug after teleporting back to my base, entering a compact machine and returning always fixes the lighting. The compact machines never have the lighting bug no matter how many times you go in and out.
- I do have a resource pack (Faithful 32x) and removing it has no effect on the bug.
- Turning off smooth lighting also has no effect on the bug other than when I purposefully use a waystone to trigger it. The light sources are individual blocks and not smoothly dispersed in a region around the light source. Furthermore, having all settings turned off or on does not affect the bug and it will always reproduce when teleporting.
- I have tried java 8 hotspot, java 8 openj9, and java 11 and the bug still persists.

These were the observations I've made trying to figure out what is causing the bug I hope it helps. I also wanted to note all of my drivers are up to date. The server I play on does not have this mod server side, we are playing All The Mods 6 with no changes or extra mods added so it's just me running Sodium Reforged.

**Comment by WenXin20** [comment]
I tried removing Flywheel and Random Patches, neither fixed it. But upon creating a new server world, I see no light glitches anywhere, so it appears maybe chunks are not getting properly updated after updating the mod. I'm not sure if it is related to another mod since I cannot find any errors in the logs relating to sodium.

**Comment by WenXin20** [comment]
After a couple of server restarts, the new world now has the lighting glitch as well... No teleporting was done.

**Comment by spoorn** [comment]
I haven't touched the lighting code myself so this is all the original Sodium and Phosphor mods.  I saw one issue in the main Sodium repo, but it doesn't look as severe as this.  Also, I've been playing on a multiplayer server myself with Sodium on it for a while with no issues, but that's on 2.8.  

Could either of you try 2.8 or lower between 2.5 and 2.8 to see which version introduced this bug?  

I'm guessing it's either Phosphor issues, or Sodium conflicting with some mod or the forge ecosystem since the same issue hasn't been reported with Fabric Sodium

**Comment by WenXin20** [comment]
Yeah, that is what I'll be doing next, starting with v2.8.

**Comment by mcullifer** [comment]
> I haven't touched the lighting code myself so this is all the original Sodium and Phosphor mods. I saw one issue in the main Sodium repo, but it doesn't look as severe as this. Also, I've been playing on a multiplayer server myself with Sodium on it for a while with no issues, but that's on 2.8.
> 
> Could either of you try 2.8 or lower between 2.5 and 2.8 to see which version introduced this bug?
> 
> I'm guessing it's either Phosphor issues, or Sodium conflicting with some mod or the forge ecosystem since the same issue hasn't been reported with Fabric Sodium

I tested 2.5-2.9.1 the bug starts at version 2.6 and persists through 2.9.1. I am unable to reproduce the bug on 2.5.

**Comment by WenXin20** [comment]
It is the same for me, v2.6+ has the same issue.

**Comment by spoorn** [comment]
Does this also happen when using a Oneshot renderer (disable Multidraw)?

**Comment by mcullifer** [comment]
> Does this also happen when using a Oneshot renderer (disable Multidraw)?

I believe OP's second image says they're using oneshot

**Comment by exentio** [comment]
I'm having a similar issue, more steps are necessary to reproduce it and the area with the issue is small, reloading the chunks resolves the problem. Basically, I use waystones to travel on a close chunk but on way higher terrain (Tinkers' slime islands), when I come back some chunks are completely dark, both indoors with lamps and lights and outside where there are no light-emitting blocks. If I go away and the chunks stop rendering, then I come back, everything's fixed. The issue is not present in 2.5 (didn't try with anything between 2.6 and 2.9, right now I'm on 2.9.1), doesn't seem to be mod-related. I'm on Linux (Arch/Artix) with the latest xf86-video-amdgpu drivers, RX480 GPU

**Comment by Shadowex3** [comment]
It's definitely something to do with teleporting. I can reproduce this reliably using journeymap's waypoint teleports. Bounce back and forth too many times and you'll start producing unlit chunks.

**Comment by WenXin20** [comment]
Odd. I don't need to teleport at all for this to happen. It happens as soon as the server loads

**Comment by spoorn** [comment]
Found out this is due to https://github.com/spoorn/sodium-forge/commit/e331f5f7143419d8307a8036a8b15fffcefb7e71

**Comment by WenXin20** [comment]
Awesome, thanks! I'll give the new version a try later.
